/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppSettingsRouteRouteImport } from './routes/_authenticated/_app/settings/route'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppNicknameDwarvesIndexRouteImport } from './routes/_authenticated/_app/nickname-dwarves/index'
import { Route as AuthenticatedAppLegendsIndexRouteImport } from './routes/_authenticated/_app/legends/index'
import { Route as AuthenticatedAppFortressIndexRouteImport } from './routes/_authenticated/_app/fortress/index'
import { Route as AuthenticatedAppActivityLogsIndexRouteImport } from './routes/_authenticated/_app/activity-logs/index'
import { Route as AuthenticatedAppSettingsNotificationsIndexRouteImport } from './routes/_authenticated/_app/settings/notifications/index'
import { Route as AuthenticatedAppSettingsLegendsIndexRouteImport } from './routes/_authenticated/_app/settings/legends/index'
import { Route as AuthenticatedAppSettingsConnectionIndexRouteImport } from './routes/_authenticated/_app/settings/connection/index'
import { Route as AuthenticatedAppSettingsAccountIndexRouteImport } from './routes/_authenticated/_app/settings/account/index'
import { Route as AuthenticatedAppLegendsWorldIndexRouteImport } from './routes/_authenticated/_app/legends/world/index'
import { Route as AuthenticatedAppLegendsStoriesIndexRouteImport } from './routes/_authenticated/_app/legends/stories/index'
import { Route as AuthenticatedAppLegendsJournalIndexRouteImport } from './routes/_authenticated/_app/legends/journal/index'
import { Route as AuthenticatedAppLegendsHistoryIndexRouteImport } from './routes/_authenticated/_app/legends/history/index'
import { Route as AuthenticatedAppLegendsArchiveIndexRouteImport } from './routes/_authenticated/_app/legends/archive/index'
import { Route as AuthenticatedAppFortressWorkIndexRouteImport } from './routes/_authenticated/_app/fortress/work/index'
import { Route as AuthenticatedAppFortressMapIndexRouteImport } from './routes/_authenticated/_app/fortress/map/index'
import { Route as AuthenticatedAppFortressItemsIndexRouteImport } from './routes/_authenticated/_app/fortress/items/index'
import { Route as AuthenticatedAppFortressDwarvesIndexRouteImport } from './routes/_authenticated/_app/fortress/dwarves/index'
import { Route as AuthenticatedAppFortressChronicleIndexRouteImport } from './routes/_authenticated/_app/fortress/chronicle/index'
import { Route as AuthenticatedAppLegendsKindIdRouteImport } from './routes/_authenticated/_app/legends/$kind/$id'
import { Route as AuthenticatedAppFortressItemsIdRouteImport } from './routes/_authenticated/_app/fortress/items/$id'
import { Route as AuthenticatedAppFortressDwarvesIdRouteImport } from './routes/_authenticated/_app/fortress/dwarves/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRouteRoute =
  AuthenticatedAppSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppNicknameDwarvesIndexRoute =
  AuthenticatedAppNicknameDwarvesIndexRouteImport.update({
    id: '/nickname-dwarves/',
    path: '/nickname-dwarves/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsIndexRoute =
  AuthenticatedAppLegendsIndexRouteImport.update({
    id: '/legends/',
    path: '/legends/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressIndexRoute =
  AuthenticatedAppFortressIndexRouteImport.update({
    id: '/fortress/',
    path: '/fortress/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivityLogsIndexRoute =
  AuthenticatedAppActivityLogsIndexRouteImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsIndexRoute =
  AuthenticatedAppSettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsLegendsIndexRoute =
  AuthenticatedAppSettingsLegendsIndexRouteImport.update({
    id: '/legends/',
    path: '/legends/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsConnectionIndexRoute =
  AuthenticatedAppSettingsConnectionIndexRouteImport.update({
    id: '/connection/',
    path: '/connection/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsAccountIndexRoute =
  AuthenticatedAppSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppLegendsWorldIndexRoute =
  AuthenticatedAppLegendsWorldIndexRouteImport.update({
    id: '/legends/world/',
    path: '/legends/world/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsStoriesIndexRoute =
  AuthenticatedAppLegendsStoriesIndexRouteImport.update({
    id: '/legends/stories/',
    path: '/legends/stories/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsJournalIndexRoute =
  AuthenticatedAppLegendsJournalIndexRouteImport.update({
    id: '/legends/journal/',
    path: '/legends/journal/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsHistoryIndexRoute =
  AuthenticatedAppLegendsHistoryIndexRouteImport.update({
    id: '/legends/history/',
    path: '/legends/history/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsArchiveIndexRoute =
  AuthenticatedAppLegendsArchiveIndexRouteImport.update({
    id: '/legends/archive/',
    path: '/legends/archive/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressWorkIndexRoute =
  AuthenticatedAppFortressWorkIndexRouteImport.update({
    id: '/fortress/work/',
    path: '/fortress/work/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressMapIndexRoute =
  AuthenticatedAppFortressMapIndexRouteImport.update({
    id: '/fortress/map/',
    path: '/fortress/map/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressItemsIndexRoute =
  AuthenticatedAppFortressItemsIndexRouteImport.update({
    id: '/fortress/items/',
    path: '/fortress/items/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressDwarvesIndexRoute =
  AuthenticatedAppFortressDwarvesIndexRouteImport.update({
    id: '/fortress/dwarves/',
    path: '/fortress/dwarves/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressChronicleIndexRoute =
  AuthenticatedAppFortressChronicleIndexRouteImport.update({
    id: '/fortress/chronicle/',
    path: '/fortress/chronicle/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLegendsKindIdRoute =
  AuthenticatedAppLegendsKindIdRouteImport.update({
    id: '/legends/$kind/$id',
    path: '/legends/$kind/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressItemsIdRoute =
  AuthenticatedAppFortressItemsIdRouteImport.update({
    id: '/fortress/items/$id',
    path: '/fortress/items/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFortressDwarvesIdRoute =
  AuthenticatedAppFortressDwarvesIdRouteImport.update({
    id: '/fortress/dwarves/$id',
    path: '/fortress/dwarves/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings': typeof AuthenticatedAppSettingsRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/activity-logs/': typeof AuthenticatedAppActivityLogsIndexRoute
  '/fortress/': typeof AuthenticatedAppFortressIndexRoute
  '/legends/': typeof AuthenticatedAppLegendsIndexRoute
  '/nickname-dwarves/': typeof AuthenticatedAppNicknameDwarvesIndexRoute
  '/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/fortress/dwarves/$id': typeof AuthenticatedAppFortressDwarvesIdRoute
  '/fortress/items/$id': typeof AuthenticatedAppFortressItemsIdRoute
  '/legends/$kind/$id': typeof AuthenticatedAppLegendsKindIdRoute
  '/fortress/chronicle/': typeof AuthenticatedAppFortressChronicleIndexRoute
  '/fortress/dwarves/': typeof AuthenticatedAppFortressDwarvesIndexRoute
  '/fortress/items/': typeof AuthenticatedAppFortressItemsIndexRoute
  '/fortress/map/': typeof AuthenticatedAppFortressMapIndexRoute
  '/fortress/work/': typeof AuthenticatedAppFortressWorkIndexRoute
  '/legends/archive/': typeof AuthenticatedAppLegendsArchiveIndexRoute
  '/legends/history/': typeof AuthenticatedAppLegendsHistoryIndexRoute
  '/legends/journal/': typeof AuthenticatedAppLegendsJournalIndexRoute
  '/legends/stories/': typeof AuthenticatedAppLegendsStoriesIndexRoute
  '/legends/world/': typeof AuthenticatedAppLegendsWorldIndexRoute
  '/settings/account/': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/connection/': typeof AuthenticatedAppSettingsConnectionIndexRoute
  '/settings/legends/': typeof AuthenticatedAppSettingsLegendsIndexRoute
  '/settings/notifications/': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/activity-logs': typeof AuthenticatedAppActivityLogsIndexRoute
  '/fortress': typeof AuthenticatedAppFortressIndexRoute
  '/legends': typeof AuthenticatedAppLegendsIndexRoute
  '/nickname-dwarves': typeof AuthenticatedAppNicknameDwarvesIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/fortress/dwarves/$id': typeof AuthenticatedAppFortressDwarvesIdRoute
  '/fortress/items/$id': typeof AuthenticatedAppFortressItemsIdRoute
  '/legends/$kind/$id': typeof AuthenticatedAppLegendsKindIdRoute
  '/fortress/chronicle': typeof AuthenticatedAppFortressChronicleIndexRoute
  '/fortress/dwarves': typeof AuthenticatedAppFortressDwarvesIndexRoute
  '/fortress/items': typeof AuthenticatedAppFortressItemsIndexRoute
  '/fortress/map': typeof AuthenticatedAppFortressMapIndexRoute
  '/fortress/work': typeof AuthenticatedAppFortressWorkIndexRoute
  '/legends/archive': typeof AuthenticatedAppLegendsArchiveIndexRoute
  '/legends/history': typeof AuthenticatedAppLegendsHistoryIndexRoute
  '/legends/journal': typeof AuthenticatedAppLegendsJournalIndexRoute
  '/legends/stories': typeof AuthenticatedAppLegendsStoriesIndexRoute
  '/legends/world': typeof AuthenticatedAppLegendsWorldIndexRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/settings/connection': typeof AuthenticatedAppSettingsConnectionIndexRoute
  '/settings/legends': typeof AuthenticatedAppSettingsLegendsIndexRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRouteRouteWithChildren
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_app/activity-logs/': typeof AuthenticatedAppActivityLogsIndexRoute
  '/_authenticated/_app/fortress/': typeof AuthenticatedAppFortressIndexRoute
  '/_authenticated/_app/legends/': typeof AuthenticatedAppLegendsIndexRoute
  '/_authenticated/_app/nickname-dwarves/': typeof AuthenticatedAppNicknameDwarvesIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/fortress/dwarves/$id': typeof AuthenticatedAppFortressDwarvesIdRoute
  '/_authenticated/_app/fortress/items/$id': typeof AuthenticatedAppFortressItemsIdRoute
  '/_authenticated/_app/legends/$kind/$id': typeof AuthenticatedAppLegendsKindIdRoute
  '/_authenticated/_app/fortress/chronicle/': typeof AuthenticatedAppFortressChronicleIndexRoute
  '/_authenticated/_app/fortress/dwarves/': typeof AuthenticatedAppFortressDwarvesIndexRoute
  '/_authenticated/_app/fortress/items/': typeof AuthenticatedAppFortressItemsIndexRoute
  '/_authenticated/_app/fortress/map/': typeof AuthenticatedAppFortressMapIndexRoute
  '/_authenticated/_app/fortress/work/': typeof AuthenticatedAppFortressWorkIndexRoute
  '/_authenticated/_app/legends/archive/': typeof AuthenticatedAppLegendsArchiveIndexRoute
  '/_authenticated/_app/legends/history/': typeof AuthenticatedAppLegendsHistoryIndexRoute
  '/_authenticated/_app/legends/journal/': typeof AuthenticatedAppLegendsJournalIndexRoute
  '/_authenticated/_app/legends/stories/': typeof AuthenticatedAppLegendsStoriesIndexRoute
  '/_authenticated/_app/legends/world/': typeof AuthenticatedAppLegendsWorldIndexRoute
  '/_authenticated/_app/settings/account/': typeof AuthenticatedAppSettingsAccountIndexRoute
  '/_authenticated/_app/settings/connection/': typeof AuthenticatedAppSettingsConnectionIndexRoute
  '/_authenticated/_app/settings/legends/': typeof AuthenticatedAppSettingsLegendsIndexRoute
  '/_authenticated/_app/settings/notifications/': typeof AuthenticatedAppSettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/settings'
    | '/auth/login/'
    | '/auth/register/'
    | '/activity-logs/'
    | '/fortress/'
    | '/legends/'
    | '/nickname-dwarves/'
    | '/settings/'
    | '/fortress/dwarves/$id'
    | '/fortress/items/$id'
    | '/legends/$kind/$id'
    | '/fortress/chronicle/'
    | '/fortress/dwarves/'
    | '/fortress/items/'
    | '/fortress/map/'
    | '/fortress/work/'
    | '/legends/archive/'
    | '/legends/history/'
    | '/legends/journal/'
    | '/legends/stories/'
    | '/legends/world/'
    | '/settings/account/'
    | '/settings/connection/'
    | '/settings/legends/'
    | '/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/activity-logs'
    | '/fortress'
    | '/legends'
    | '/nickname-dwarves'
    | '/settings'
    | '/fortress/dwarves/$id'
    | '/fortress/items/$id'
    | '/legends/$kind/$id'
    | '/fortress/chronicle'
    | '/fortress/dwarves'
    | '/fortress/items'
    | '/fortress/map'
    | '/fortress/work'
    | '/legends/archive'
    | '/legends/history'
    | '/legends/journal'
    | '/legends/stories'
    | '/legends/world'
    | '/settings/account'
    | '/settings/connection'
    | '/settings/legends'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_app'
    | '/auth/callback'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_app/activity-logs/'
    | '/_authenticated/_app/fortress/'
    | '/_authenticated/_app/legends/'
    | '/_authenticated/_app/nickname-dwarves/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/fortress/dwarves/$id'
    | '/_authenticated/_app/fortress/items/$id'
    | '/_authenticated/_app/legends/$kind/$id'
    | '/_authenticated/_app/fortress/chronicle/'
    | '/_authenticated/_app/fortress/dwarves/'
    | '/_authenticated/_app/fortress/items/'
    | '/_authenticated/_app/fortress/map/'
    | '/_authenticated/_app/fortress/work/'
    | '/_authenticated/_app/legends/archive/'
    | '/_authenticated/_app/legends/history/'
    | '/_authenticated/_app/legends/journal/'
    | '/_authenticated/_app/legends/stories/'
    | '/_authenticated/_app/legends/world/'
    | '/_authenticated/_app/settings/account/'
    | '/_authenticated/_app/settings/connection/'
    | '/_authenticated/_app/settings/legends/'
    | '/_authenticated/_app/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/_app/nickname-dwarves/': {
      id: '/_authenticated/_app/nickname-dwarves/'
      path: '/nickname-dwarves'
      fullPath: '/nickname-dwarves/'
      preLoaderRoute: typeof AuthenticatedAppNicknameDwarvesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/': {
      id: '/_authenticated/_app/legends/'
      path: '/legends'
      fullPath: '/legends/'
      preLoaderRoute: typeof AuthenticatedAppLegendsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/': {
      id: '/_authenticated/_app/fortress/'
      path: '/fortress'
      fullPath: '/fortress/'
      preLoaderRoute: typeof AuthenticatedAppFortressIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/activity-logs/': {
      id: '/_authenticated/_app/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs/'
      preLoaderRoute: typeof AuthenticatedAppActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/notifications/': {
      id: '/_authenticated/_app/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/_app/settings/legends/': {
      id: '/_authenticated/_app/settings/legends/'
      path: '/legends'
      fullPath: '/settings/legends/'
      preLoaderRoute: typeof AuthenticatedAppSettingsLegendsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/_app/settings/connection/': {
      id: '/_authenticated/_app/settings/connection/'
      path: '/connection'
      fullPath: '/settings/connection/'
      preLoaderRoute: typeof AuthenticatedAppSettingsConnectionIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/_app/settings/account/': {
      id: '/_authenticated/_app/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/_app/legends/world/': {
      id: '/_authenticated/_app/legends/world/'
      path: '/legends/world'
      fullPath: '/legends/world/'
      preLoaderRoute: typeof AuthenticatedAppLegendsWorldIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/stories/': {
      id: '/_authenticated/_app/legends/stories/'
      path: '/legends/stories'
      fullPath: '/legends/stories/'
      preLoaderRoute: typeof AuthenticatedAppLegendsStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/journal/': {
      id: '/_authenticated/_app/legends/journal/'
      path: '/legends/journal'
      fullPath: '/legends/journal/'
      preLoaderRoute: typeof AuthenticatedAppLegendsJournalIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/history/': {
      id: '/_authenticated/_app/legends/history/'
      path: '/legends/history'
      fullPath: '/legends/history/'
      preLoaderRoute: typeof AuthenticatedAppLegendsHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/archive/': {
      id: '/_authenticated/_app/legends/archive/'
      path: '/legends/archive'
      fullPath: '/legends/archive/'
      preLoaderRoute: typeof AuthenticatedAppLegendsArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/work/': {
      id: '/_authenticated/_app/fortress/work/'
      path: '/fortress/work'
      fullPath: '/fortress/work/'
      preLoaderRoute: typeof AuthenticatedAppFortressWorkIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/map/': {
      id: '/_authenticated/_app/fortress/map/'
      path: '/fortress/map'
      fullPath: '/fortress/map/'
      preLoaderRoute: typeof AuthenticatedAppFortressMapIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/items/': {
      id: '/_authenticated/_app/fortress/items/'
      path: '/fortress/items'
      fullPath: '/fortress/items/'
      preLoaderRoute: typeof AuthenticatedAppFortressItemsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/dwarves/': {
      id: '/_authenticated/_app/fortress/dwarves/'
      path: '/fortress/dwarves'
      fullPath: '/fortress/dwarves/'
      preLoaderRoute: typeof AuthenticatedAppFortressDwarvesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/chronicle/': {
      id: '/_authenticated/_app/fortress/chronicle/'
      path: '/fortress/chronicle'
      fullPath: '/fortress/chronicle/'
      preLoaderRoute: typeof AuthenticatedAppFortressChronicleIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/legends/$kind/$id': {
      id: '/_authenticated/_app/legends/$kind/$id'
      path: '/legends/$kind/$id'
      fullPath: '/legends/$kind/$id'
      preLoaderRoute: typeof AuthenticatedAppLegendsKindIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/items/$id': {
      id: '/_authenticated/_app/fortress/items/$id'
      path: '/fortress/items/$id'
      fullPath: '/fortress/items/$id'
      preLoaderRoute: typeof AuthenticatedAppFortressItemsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fortress/dwarves/$id': {
      id: '/_authenticated/_app/fortress/dwarves/$id'
      path: '/fortress/dwarves/$id'
      fullPath: '/fortress/dwarves/$id'
      preLoaderRoute: typeof AuthenticatedAppFortressDwarvesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteRouteChildren {
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppSettingsAccountIndexRoute: typeof AuthenticatedAppSettingsAccountIndexRoute
  AuthenticatedAppSettingsConnectionIndexRoute: typeof AuthenticatedAppSettingsConnectionIndexRoute
  AuthenticatedAppSettingsLegendsIndexRoute: typeof AuthenticatedAppSettingsLegendsIndexRoute
  AuthenticatedAppSettingsNotificationsIndexRoute: typeof AuthenticatedAppSettingsNotificationsIndexRoute
}

const AuthenticatedAppSettingsRouteRouteChildren: AuthenticatedAppSettingsRouteRouteChildren =
  {
    AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
    AuthenticatedAppSettingsAccountIndexRoute:
      AuthenticatedAppSettingsAccountIndexRoute,
    AuthenticatedAppSettingsConnectionIndexRoute:
      AuthenticatedAppSettingsConnectionIndexRoute,
    AuthenticatedAppSettingsLegendsIndexRoute:
      AuthenticatedAppSettingsLegendsIndexRoute,
    AuthenticatedAppSettingsNotificationsIndexRoute:
      AuthenticatedAppSettingsNotificationsIndexRoute,
  }

const AuthenticatedAppSettingsRouteRouteWithChildren =
  AuthenticatedAppSettingsRouteRoute._addFileChildren(
    AuthenticatedAppSettingsRouteRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppSettingsRouteRoute: typeof AuthenticatedAppSettingsRouteRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppActivityLogsIndexRoute: typeof AuthenticatedAppActivityLogsIndexRoute
  AuthenticatedAppFortressIndexRoute: typeof AuthenticatedAppFortressIndexRoute
  AuthenticatedAppLegendsIndexRoute: typeof AuthenticatedAppLegendsIndexRoute
  AuthenticatedAppNicknameDwarvesIndexRoute: typeof AuthenticatedAppNicknameDwarvesIndexRoute
  AuthenticatedAppFortressDwarvesIdRoute: typeof AuthenticatedAppFortressDwarvesIdRoute
  AuthenticatedAppFortressItemsIdRoute: typeof AuthenticatedAppFortressItemsIdRoute
  AuthenticatedAppLegendsKindIdRoute: typeof AuthenticatedAppLegendsKindIdRoute
  AuthenticatedAppFortressChronicleIndexRoute: typeof AuthenticatedAppFortressChronicleIndexRoute
  AuthenticatedAppFortressDwarvesIndexRoute: typeof AuthenticatedAppFortressDwarvesIndexRoute
  AuthenticatedAppFortressItemsIndexRoute: typeof AuthenticatedAppFortressItemsIndexRoute
  AuthenticatedAppFortressMapIndexRoute: typeof AuthenticatedAppFortressMapIndexRoute
  AuthenticatedAppFortressWorkIndexRoute: typeof AuthenticatedAppFortressWorkIndexRoute
  AuthenticatedAppLegendsArchiveIndexRoute: typeof AuthenticatedAppLegendsArchiveIndexRoute
  AuthenticatedAppLegendsHistoryIndexRoute: typeof AuthenticatedAppLegendsHistoryIndexRoute
  AuthenticatedAppLegendsJournalIndexRoute: typeof AuthenticatedAppLegendsJournalIndexRoute
  AuthenticatedAppLegendsStoriesIndexRoute: typeof AuthenticatedAppLegendsStoriesIndexRoute
  AuthenticatedAppLegendsWorldIndexRoute: typeof AuthenticatedAppLegendsWorldIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppSettingsRouteRoute:
    AuthenticatedAppSettingsRouteRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppActivityLogsIndexRoute:
    AuthenticatedAppActivityLogsIndexRoute,
  AuthenticatedAppFortressIndexRoute: AuthenticatedAppFortressIndexRoute,
  AuthenticatedAppLegendsIndexRoute: AuthenticatedAppLegendsIndexRoute,
  AuthenticatedAppNicknameDwarvesIndexRoute:
    AuthenticatedAppNicknameDwarvesIndexRoute,
  AuthenticatedAppFortressDwarvesIdRoute:
    AuthenticatedAppFortressDwarvesIdRoute,
  AuthenticatedAppFortressItemsIdRoute: AuthenticatedAppFortressItemsIdRoute,
  AuthenticatedAppLegendsKindIdRoute: AuthenticatedAppLegendsKindIdRoute,
  AuthenticatedAppFortressChronicleIndexRoute:
    AuthenticatedAppFortressChronicleIndexRoute,
  AuthenticatedAppFortressDwarvesIndexRoute:
    AuthenticatedAppFortressDwarvesIndexRoute,
  AuthenticatedAppFortressItemsIndexRoute:
    AuthenticatedAppFortressItemsIndexRoute,
  AuthenticatedAppFortressMapIndexRoute: AuthenticatedAppFortressMapIndexRoute,
  AuthenticatedAppFortressWorkIndexRoute:
    AuthenticatedAppFortressWorkIndexRoute,
  AuthenticatedAppLegendsArchiveIndexRoute:
    AuthenticatedAppLegendsArchiveIndexRoute,
  AuthenticatedAppLegendsHistoryIndexRoute:
    AuthenticatedAppLegendsHistoryIndexRoute,
  AuthenticatedAppLegendsJournalIndexRoute:
    AuthenticatedAppLegendsJournalIndexRoute,
  AuthenticatedAppLegendsStoriesIndexRoute:
    AuthenticatedAppLegendsStoriesIndexRoute,
  AuthenticatedAppLegendsWorldIndexRoute:
    AuthenticatedAppLegendsWorldIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
