export const SSTEIGER_NAMES = [
  'Urist Mc OSHA Violation',
  'Gravy Jones',
  'Bilbo Swaggins',
  'Sir Loin of Beef',
  'Thighs Wide Shut',
  'Pickaxe Daddy',
  'Doug Dimmadebt',
  'Groin Stronghammer',
  'The Yeast Beast',
  'BBL Balrog',
  'Count Flatula',
  'Flint Eastwood',
  'The Load-Bearing Idiot',
  'Bong Solo',
  'Girth Brooks',
  'Dwayne the Stockpile Johnson',
  "Moist von Lipwig's Cousin, Damp",
  'Wombat Combat',
  'Feral Accountant',
  'The Emotional Support Goblin',
  'Sir Cumference',
  'Grundle the Unwashed',
  'Tax Evasion',
  'Industrial Accident',
  'Legally a Turnip',
  'The Suspiciously Wide Mayor',
  'Soggy Bottom Bill',
  'The Breastmilk Alchemist',
  'Costco Necromancer',
  'Pubert the Uninvited',
  'Stank Sinatra',
  'Crustopher Columbus',
  'The Hash-Slinging Basher',
  'Balthazar Ballsack',
  'Tungsten Tits',
  'Medium-Sized Chungus',
  'Three Beards No Dwarf',
  'Union-Mandated Nap',
  'The Wrong Lever',
  'Greg the Granade',
  'Whiskey Business',
  'The Forbidden Meatball',
  'Scrotus Maximus',
  'Not Allowed Near the Well',
  'The Prostate Prospector',
  'Live Laugh Cave-In',
  'Absolutely Not a Vampire',
  'His Majesty the Plumbing Incident',
  'John Dwarf Kennedy',
  'The Broadfather',
  'Beef Wellington III',
  'Grout Expectations',
  "Shaquille O'Meal",
  'Spleen McQueen',
  'The Wort Whisperer',
  'Globert',
  'Sir Honks-a-Lot',
  'Dumptruck Dumbledore',
  'The Seventh Chin',
  "Methuselah's Discord Kitten",
  'Scrotie McBoogerballs',
  'The Unlicensed Proctologist',
  'Lard Farquaad',
  'Dildo Baggins',
  'Bunion Jack',
  'Throbbin Hood',
  'The Tenderloin Terminator',
  'Gravy Seals',
  'Crumb Dumpster',
  'The Fungal Patriarch',
  'Balls Deep Rock Galactic',
  'Slabitha',
  'Chungus Amongus',
  'Fart Garfunkel',
  'The Floor Is Grandma',
  'Gneiss Package',
  'Rock Bottom Randy',
  'The Morally Flexible Butcher',
  'Hairy Plopper',
  'Bowel Movement Enthusiast',
  'The Duke of Mucus',
  'Blunt Force Brenda',
  'The Honorable Sack of Ham',
  'Doug the Hole',
  'Emergency Contact: Nobody',
  'The Last Beerbender',
  'Plump Fiction',
  'Lord of the Onion Rings',
  'The Liability',
  'Thicc Astley',
  'Rumplestiltskin Condition',
  'Ham Solo',
  'The Wet Bandage',
  'Municipal Waste Dave',
  'Stone Cold Steve Autism',
  'The Unwashed Mass',
  'Professional Stair Victim',
  'Urinal the Grey',
  'The Structural Support Himbo',
  'Butt Plug Executive',
  'Ballsamic Vinegar',
  'Balls of Fury',
  'The Biggest Dick in the Room',
  'Concrete Carl',
  'The Pickaxe Tax',
  'Dwayne the Rock Bottom',
  'Legally Distinct Gimli',
  'The Unpaid Intern',
  'The Designated Casualty',
  'A Minor Inconvenience',
  'Six Inches from Being a Problem',
  'The Ice Cream Cone',
  'A Compressed Tall Guy',
  'Norman Nutclap',
  'Legs Wide Shut',
  'Deep in Dept Doug',
]

/** Names VonGalactic gave his dwarves on stream, transcribed from his videos. */
export const VONGALACTIC_NAMES = [
  //'Driftwood Muncher',
  'Space Potato',
  'Dr. Methylene Blue, PhD',
  //'Curling Stone 2 Unleashed',
  'Three Kobolds in a Trenchcoat',
  'Lump in a Bag',
  'Human with Dwarfism',
  'Rufus the Bulldog',
  'Mr. Potato Head',
  'Dwarfy McDwarfface',
  'Ice Cube Jr.',
  //'Clayborn',
  'Coco',
  'Sven',
  'Crinkled',
  'OSHA Supervisor',
  'Fluid Druid',
  'Tiny Toes Thompson',
  'Elf Fister',
  'Octavius',
  'Neo',
  'Lever Enjoyer',
  'Test Dummy',
  'Grundle Puncher',
  'Fred Durst the Vampire',
  'Dangerous Narrative',
  'Girl Failure',
  'Dick Wolf',
  'Dino Nuggie',
  'Weed McGee',
  'Sir Digby Chicken Caesar',
  'Unkillable Urist',
  'Big Willie',
  'Willie Milka',
  'Velveeta Cheese',
  'Mike Oxlong',
  'Dixie Normous',
  'Peter Griffin',
  'Flat Earth',
  'Sack Biter',
  'Girl Piston',
  'Dick Twister',
  'Gland Lover',
  'Samurai Cop',
  'Free Dwarf',
  'Random World Eater',
  'Puppy Snipper',
  'British Furry',
  'Installation Wizard',
  "Von's Sentient Kimono",
  'Wallace and Gromit',
  'Kenshiro',
  'Bruce Lee',
  'Big Bongus',
  'Fistula',
  'Mr. Booze',
  'Toad Frogman',
  'Big Fat Head',
  'Mo Problems',
  'Baby Smasher',
  'Urist Jagger',
  'Schlongavius',
  'Lemon Lad',
  'Beanie Weenie',
  'The Potato Contraceptive',
  'Palm Beach Dwarfrey',
  'Delilah Sandwich',
  'Big Badonka Wonkers',
  'Samurai Jack',
  'Incontinentia Buttocks',
  'Christmas Princess',
  'Cocktaster',
  'Lord Vetinari',
  'Giant Dad',
  'Bane',
  'Emily Dwarf',
  'Biggest Milker',
  'Foot Fungus',
  'Daffy',
  'Inch Master',
  'Chris Pratt',
  'Biggie Cheese',
  'Jerkinghoff',
  'Performance Anxiety',
  'Lich with BBL',
  'Knobby Knobs',
  'The Pointer',
  'Bushy Hammer Nipple',
  'Bend Over',
  'Fish and Chips',
  'Duck Ass',
  'Norwood Reaper',
]
